import { Character } from '@/types';
import { Timestamp } from 'firebase/firestore';

export const seedCharacters: Omit<Character, 'id'>[] = [
  {
    name: 'Tech-a-saurus Rex',
    companySymbol: 'TECH',
    companyName: 'Tech Giant Corp',
    type: 'Technology',
    description: 'The mighty ruler of the tech jungle! This character represents a massive technology company that creates smartphones, computers, and software used by billions worldwide.',
    imageUrl: '🦖',
    abilities: ['Innovation Boost', 'Digital Domination', 'Cloud Power'],
    rarity: 'epic',
    marketData: {
      currentPrice: 2500,
      priceChange: 125,
      priceChangePercent: 5.26,
      lastUpdated: Timestamp.now(),
      marketCap: 2500000000,
      volume: 50000,
    },
  },
  {
    name: 'Burger Buddy',
    companySymbol: 'BURG',
    companyName: 'Global Burgers Inc',
    type: 'Food & Beverage',
    description: 'Your friendly neighborhood burger expert! Represents a worldwide fast-food chain serving millions of hungry customers every day.',
    imageUrl: '🍔',
    abilities: ['Global Reach', 'Brand Power', 'Customer Loyalty'],
    rarity: 'common',
    marketData: {
      currentPrice: 800,
      priceChange: -15,
      priceChangePercent: -1.84,
      lastUpdated: Timestamp.now(),
      marketCap: 450000000,
      volume: 30000,
    },
  },
  {
    name: 'Lightning Bolt',
    companySymbol: 'ELEC',
    companyName: 'Tesla Motors',
    type: 'Automotive',
    description: 'Zoom zoom! The fastest electric vehicle maker on the planet. Building cool cars that run on electricity instead of gas!',
    imageUrl: '⚡',
    abilities: ['Speed Demon', 'Clean Energy', 'Future Vision'],
    rarity: 'epic',
    marketData: {
      currentPrice: 3200,
      priceChange: 200,
      priceChangePercent: 6.67,
      lastUpdated: Timestamp.now(),
      marketCap: 800000000,
      volume: 75000,
    },
  },
  {
    name: 'Package Pal',
    companySymbol: 'SHIP',
    companyName: 'Express Delivery Co',
    type: 'E-Commerce',
    description: 'Delivers everything to your door super fast! Runs the biggest online store where you can buy almost anything and get it delivered quickly.',
    imageUrl: '📦',
    abilities: ['Fast Shipping', 'Everything Store', 'Prime Power'],
    rarity: 'legendary',
    marketData: {
      currentPrice: 4500,
      priceChange: 180,
      priceChangePercent: 4.17,
      lastUpdated: Timestamp.now(),
      marketCap: 1800000000,
      volume: 100000,
    },
  },
  {
    name: 'Dr. Pill',
    companySymbol: 'HEAL',
    companyName: 'HealthCare Systems',
    type: 'Healthcare',
    description: 'Keeping people healthy! Makes medicines and vaccines that help sick people feel better.',
    imageUrl: '💊',
    abilities: ['Healing Touch', 'Research Pro', 'Life Saver'],
    rarity: 'rare',
    marketData: {
      currentPrice: 1800,
      priceChange: 50,
      priceChangePercent: 2.86,
      lastUpdated: Timestamp.now(),
      marketCap: 600000000,
      volume: 40000,
    },
  },
  {
    name: 'Game Master',
    companySymbol: 'GAME',
    companyName: 'Gaming Entertainment',
    type: 'Entertainment',
    description: 'Level up! Creates amazing video games and gaming consoles that millions of kids and adults love to play.',
    imageUrl: '🎮',
    abilities: ['Fun Creator', 'Entertainment King', 'Joy Bringer'],
    rarity: 'rare',
    marketData: {
      currentPrice: 1500,
      priceChange: 75,
      priceChangePercent: 5.26,
      lastUpdated: Timestamp.now(),
      marketCap: 400000000,
      volume: 35000,
    },
  },
  {
    name: 'Solar Sam',
    companySymbol: 'SUN',
    companyName: 'Solar Energy Corp',
    type: 'Energy',
    description: 'Powered by the sun! Captures energy from sunlight to create clean electricity for homes and businesses.',
    imageUrl: '☀️',
    abilities: ['Clean Energy', 'Sun Power', 'Eco Warrior'],
    rarity: 'common',
    marketData: {
      currentPrice: 650,
      priceChange: 30,
      priceChangePercent: 4.84,
      lastUpdated: Timestamp.now(),
      marketCap: 200000000,
      volume: 25000,
    },
  },
  {
    name: 'Sneaker Sprint',
    companySymbol: 'SHOE',
    companyName: 'Athletic Footwear Inc',
    type: 'Retail',
    description: 'Just do it! Makes the coolest sneakers and sports gear for athletes and kids who love to play sports.',
    imageUrl: '👟',
    abilities: ['Speed Boost', 'Style Icon', 'Athletic Pro'],
    rarity: 'common',
    marketData: {
      currentPrice: 900,
      priceChange: -20,
      priceChangePercent: -2.17,
      lastUpdated: Timestamp.now(),
      marketCap: 350000000,
      volume: 45000,
    },
  },
  {
    name: 'Movie Magic',
    companySymbol: 'FILM',
    companyName: 'Entertainment Studios',
    type: 'Entertainment',
    description: 'Lights, camera, action! Creates blockbuster movies, TV shows, and theme parks that bring stories to life.',
    imageUrl: '🎬',
    abilities: ['Storyteller', 'Magic Maker', 'Dream Creator'],
    rarity: 'rare',
    marketData: {
      currentPrice: 2000,
      priceChange: 100,
      priceChangePercent: 5.26,
      lastUpdated: Timestamp.now(),
      marketCap: 550000000,
      volume: 40000,
    },
  },
  {
    name: 'Credit Captain',
    companySymbol: 'BANK',
    companyName: 'Global Bank Corp',
    type: 'Finance',
    description: 'Money matters! A huge bank that helps people save money, get loans, and use credit cards safely.',
    imageUrl: '💳',
    abilities: ['Money Manager', 'Trust Builder', 'Financial Shield'],
    rarity: 'common',
    marketData: {
      currentPrice: 750,
      priceChange: 15,
      priceChangePercent: 2.04,
      lastUpdated: Timestamp.now(),
      marketCap: 300000000,
      volume: 35000,
    },
  },
  {
    name: 'Coffee Cloud',
    companySymbol: 'CAFE',
    companyName: 'Premium Coffee Shops',
    type: 'Food & Beverage',
    description: 'Wake up and smell the coffee! Serves delicious coffee drinks and snacks in cozy cafes around the world.',
    imageUrl: '☕',
    abilities: ['Energy Boost', 'Community Hub', 'Morning Power'],
    rarity: 'common',
    marketData: {
      currentPrice: 700,
      priceChange: -10,
      priceChangePercent: -1.41,
      lastUpdated: Timestamp.now(),
      marketCap: 280000000,
      volume: 28000,
    },
  },
  {
    name: 'Rocket Rider',
    companySymbol: 'SPCE',
    companyName: 'Space Exploration Co',
    type: 'Aerospace',
    description: 'To infinity and beyond! Builds rockets and spacecraft to explore space and maybe one day take tourists to the stars!',
    imageUrl: '🚀',
    abilities: ['Sky High', 'Future Tech', 'Bold Explorer'],
    rarity: 'legendary',
    marketData: {
      currentPrice: 5000,
      priceChange: 250,
      priceChangePercent: 5.26,
      lastUpdated: Timestamp.now(),
      marketCap: 1000000000,
      volume: 60000,
    },
  },
];
